"""Rewrite demo.html's generated parts from the live sources.

- The app stylesheet block, between its BEGIN/END markers: frontend/src/style.css with every rule
  scoped under .screen, and the viewport resolved for the demo's 390x658 phone screen (vw and dvh
  pinned, the phone media query unwrapped, the desktop one dropped).
- The questionnaire snapshot (const Q) and the chat's sample questions (const CHAT_SAMPLES), from
  config/app.json.

Run from the repository root: python3 .claude/skills/align-demo/sync_demo.py
"""
import json
import re
from pathlib import Path

DEMO = Path("frontend/public/demo.html")
VW, VH = 390, 658
BEGIN = "/* BEGIN generated by .claude/skills/align-demo/sync_demo.py */\n"
END = "/* END generated */\n"


def pin(value):
    value = re.sub(r"(\d+(?:\.\d+)?)dvh", lambda m: f"{float(m.group(1)) * VH / 100:g}px", value)
    return re.sub(r"(\d+(?:\.\d+)?)vw", lambda m: f"{float(m.group(1)) * VW / 100:g}px", value)


def scope_selector(sel):
    sel = " ".join(sel.split())
    if sel == "html":
        return None
    for root in (":root", "body", "#root"):
        if sel.startswith(root):
            return ".screen" + sel[len(root):]
    return ".screen " + sel


def split_top(prelude):
    """Split a selector list on the commas outside parentheses, so :is(a, b) stays whole."""
    parts, depth, cur = [], 0, ""
    for ch in prelude:
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
            continue
        depth += ch == "("
        depth -= ch == ")"
        cur += ch
    return parts + [cur]


def blocks(text):
    i = 0
    while (j := text.find("{", i)) >= 0:
        depth, k = 1, j + 1
        while depth:
            depth += {"{": 1, "}": -1}.get(text[k], 0)
            k += 1
        yield text[i:j].strip(), text[j + 1:k - 1]
        i = k


def emit(text, out):
    for prelude, body in blocks(text):
        if prelude.startswith("@media"):
            if "min-width: 48rem" in prelude:
                continue
            if "max-width: 47.99rem" in prelude:
                emit(body, out)
                continue
            inner = []
            emit(body, inner)
            out.append(prelude + " {\n" + "\n".join("  " + r for r in inner) + "\n}")
        elif prelude.startswith(("@keyframes", "@property")):
            out.append(prelude + " { " + " ".join(body.split()) + " }")
        else:
            sels = [s for s in map(scope_selector, split_top(prelude)) if s]
            if sels:
                decls = " ".join(line.strip() for line in pin(body).strip().splitlines())
                out.append(", ".join(sels) + " { " + decls + " }")


def scoped_css():
    src = re.sub(r"/\*.*?\*/", "", Path("frontend/src/style.css").read_text(), flags=re.S)
    out = []
    emit(src, out)
    return "\n".join(out) + "\n"


def js(value):
    return re.sub(r'"(\w+)":', r"\1:", json.dumps(value, ensure_ascii=False))


def questionnaire_js(q):
    questions = []
    for question in q["questions"]:
        question = dict(question)
        choices = question.pop("choices")
        nested = [(k, question.pop(k)) for k in ("amounts", "portions", "additions") if k in question]
        lines = [f"      {k}: {js(v)}," for k, v in nested]
        lines.append("      choices: [\n" + ",\n".join("        " + js(c) for c in choices) + "\n      ]")
        questions.append("    " + js(question)[:-1] + ",\n" + "\n".join(lines) + "\n    }")
    rules = ",\n".join("    " + js(r) for r in q["rules"])
    return (f"const Q = {{\n  version: {q['version']},\n  questions: [\n" + ",\n".join(questions)
            + f"\n  ],\n  rules: [\n{rules}\n  ]\n}};")


def replace_between(text, start, end, new):
    i = text.index(start)
    j = text.index(end, i)
    return text[:i] + new + text[j + len(end):]


config = json.loads(Path("config/app.json").read_text())
demo = DEMO.read_text()
demo = replace_between(demo, BEGIN, END, BEGIN + scoped_css() + END)
demo = replace_between(demo, "const Q = {", "\n};", questionnaire_js(config["questionnaire"]))
samples = ",\n".join("  " + js(s) for s in config["chat"]["sample_questions"])
demo = replace_between(demo, "const CHAT_SAMPLES = [", "\n];", f"const CHAT_SAMPLES = [\n{samples}\n];")
DEMO.write_text(demo)
