#!/bin/bash
# Deploys both stacks. The Cognito callback URL and API CORS origin need the CloudFront URL,
# which only exists after the main stack's first deploy — so each run converges: deploy with
# what is known, then re-deploy both stacks with the now-known URL (no-op when unchanged).
set -euo pipefail
cd "$(dirname "$0")/.."
source scripts/aws-config.sh
source scripts/params.sh

# Optional environment suffix (e.g. "dev") deploys a fully isolated stack pair alongside the
# default one; the Cognito domain prefix must vary with it because domains are global.
ENV_SUFFIX="${1:+-$1}"

APP="diet-tracker${ENV_SUFFIX}"
ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
ARTIFACTS_BUCKET="${APP}-artifacts-${ACCOUNT}"
aws s3api head-bucket --bucket "$ARTIFACTS_BUCKET" 2>/dev/null || aws s3 mb "s3://${ARTIFACTS_BUCKET}"

rm -rf build/lambda
mkdir -p build/lambda
cp -r src/. build/lambda/
find build/lambda -type d -name __pycache__ -exec rm -rf {} +
cp config/app.json build/lambda/

stack_output() {
  local out
  if ! out=$(aws cloudformation describe-stacks --stack-name "$1" \
      --query "Stacks[0].Outputs[?OutputKey=='$2'].OutputValue" --output text 2>&1); then
    case "$out" in
      *"does not exist"*) echo ""; return 0 ;;
      *) echo "stack_output failed for $1/$2: $out" >&2; return 1 ;;
    esac
  fi
  [ "$out" = "None" ] && out=""
  echo "$out"
}

deploy_cognito() {
  local callbacks="http://localhost:8000/"
  [ -n "$1" ] && callbacks="${callbacks},$1/"
  aws cloudformation package --template-file scripts/template-cognito.yaml \
    --s3-bucket "$ARTIFACTS_BUCKET" --output-template-file build/template-cognito.pkg.yaml
  aws cloudformation deploy --template-file build/template-cognito.pkg.yaml \
    --stack-name "${APP}-cognito" --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-fail-on-empty-changeset \
    --parameter-overrides GoogleClientId="$GOOGLE_CLIENT_ID" GoogleClientSecret="$GOOGLE_CLIENT_SECRET" \
      AllowedEmails="$ALLOWED_EMAILS" CallbackUrls="$callbacks" DomainPrefix="diet-trk${ENV_SUFFIX}"
}

# Every hour a schedule's cron is built from is passed on each deploy: CloudFormation keeps the
# previous value of any parameter a deploy leaves out, so a template default is inert once the
# stack exists. The weigh-in slot is declared in config/app.json and lifted out here because an
# EventBridge cron is fixed when the stack deploys.
app_config() {
  python3 -c "import json; print(json.load(open('config/app.json'))$1)"
}

deploy_main() {
  local origins="http://localhost:8000"
  [ -n "$1" ] && origins="${origins},$1"
  aws cloudformation package --template-file scripts/template.yaml \
    --s3-bucket "$ARTIFACTS_BUCKET" --output-template-file build/template.pkg.yaml
  local user_pool_id
  local user_pool_client_id
  user_pool_id=$(stack_output "${APP}-cognito" UserPoolId)
  user_pool_client_id=$(stack_output "${APP}-cognito" UserPoolClientId)
  aws cloudformation deploy --template-file build/template.pkg.yaml \
    --stack-name "$APP" --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-fail-on-empty-changeset \
    --parameter-overrides SesSender="$SES_SENDER" AllowedOrigins="$origins" \
      UserPoolId="$user_pool_id" \
      UserPoolClientId="$user_pool_client_id" \
      WeighInWeekday="$(app_config "['weight']['weigh_in']['weekday']")" \
      WeighInHour="$(app_config "['weight']['weigh_in']['hour']")" \
      RagApiUrl="${RAG_API_URL:-}" \
      ChatDailyLimit="$CHAT_DAILY_LIMIT" \
      ChatDailyLimitOverrides="$CHAT_DAILY_LIMIT_OVERRIDES"
}

FRONTEND_URL=$(stack_output "$APP" FrontendUrl)
deploy_cognito "$FRONTEND_URL"
deploy_main "$FRONTEND_URL"

CONVERGED_URL=$(stack_output "$APP" FrontendUrl)
if [ "$CONVERGED_URL" != "$FRONTEND_URL" ]; then
  deploy_cognito "$CONVERGED_URL"
  deploy_main "$CONVERGED_URL"
fi

HOSTED_UI_DOMAIN=$(stack_output "${APP}-cognito" HostedUiDomain)
CLIENT_ID=$(stack_output "${APP}-cognito" UserPoolClientId)
API_URL=$(stack_output "$APP" ApiUrl)
DAY_END_HOUR=$(stack_output "$APP" DayEndHour)
FIRST_MEAL_HOUR=$(stack_output "$APP" FirstMealHour)
MEAL_GAP_HOURS=$(stack_output "$APP" MealGapHours)
# public/ may be absent on a fresh clone — its only content is this gitignored file.
mkdir -p frontend/public
# The allowlist's first entry is the app owner, shown to rejected sign-ins as the access contact.
cat > frontend/public/config.js <<EOF
// Generated by scripts/deploy.sh — do not edit by hand.
window.CONFIG = {
  cognitoDomain: "$HOSTED_UI_DOMAIN",
  clientId: "$CLIENT_ID",
  apiUrl: "$API_URL",
  redirectUri: window.location.origin + "/",
  rootEmail: "${ALLOWED_EMAILS%%,*}",
  dayEndHour: ${DAY_END_HOUR},
  firstMealHour: ${FIRST_MEAL_HOUR},
  mealGapHours: ${MEAL_GAP_HOURS},
};
EOF

[ -x scripts/sync-frontend.sh ] && scripts/sync-frontend.sh "${1:-}"
FRONTEND_URL=$(stack_output "$APP" FrontendUrl)
echo "Deployed. Frontend: ${FRONTEND_URL}"
